import type {
  ActivityItem,
  DashboardStats,
  Founder,
  InvestmentMemo,
  PipelineItem,
  SearchResult,
  Startup,
} from "@/types";

export const dashboardStats: DashboardStats = {
  activeDeals: 24,
  pipelineValue: 186_000_000,
  memosThisMonth: 12,
  foundersTracked: 87,
  avgConviction: 72,
  closedDealsYtd: 5,
};

export const pipeline: PipelineItem[] = [
  {
    id: "p1",
    name: "NovaGrid",
    sector: "Climate Tech",
    stage: "due_diligence",
    amount: 8_000_000,
    updatedAt: "2026-07-18T10:00:00Z",
  },
  {
    id: "p2",
    name: "Lattice AI",
    sector: "Enterprise AI",
    stage: "term_sheet",
    amount: 12_000_000,
    updatedAt: "2026-07-17T14:30:00Z",
  },
  {
    id: "p3",
    name: "Harbor Health",
    sector: "HealthTech",
    stage: "screening",
    amount: 5_500_000,
    updatedAt: "2026-07-16T09:15:00Z",
  },
  {
    id: "p4",
    name: "PulsePay",
    sector: "FinTech",
    stage: "sourcing",
    amount: 3_000_000,
    updatedAt: "2026-07-15T16:45:00Z",
  },
  {
    id: "p5",
    name: "Orbital Ops",
    sector: "Aerospace",
    stage: "due_diligence",
    amount: 15_000_000,
    updatedAt: "2026-07-14T11:20:00Z",
  },
];

export const recentActivity: ActivityItem[] = [
  {
    id: "a1",
    type: "memo",
    title: "Memo approved — Lattice AI",
    description: "Investment committee approved Series A memo",
    timestamp: "2026-07-18T15:20:00Z",
  },
  {
    id: "a2",
    type: "meeting",
    title: "Founder call — NovaGrid",
    description: "Technical deep-dive with CTO Priya Shah",
    timestamp: "2026-07-18T11:00:00Z",
  },
  {
    id: "a3",
    type: "score",
    title: "Risk score updated — Harbor Health",
    description: "Regulatory risk flagged as medium-high",
    timestamp: "2026-07-17T18:40:00Z",
  },
  {
    id: "a4",
    type: "note",
    title: "Partner note added — PulsePay",
    description: "Strong unit economics; request cohort analysis",
    timestamp: "2026-07-17T09:05:00Z",
  },
];

export const founders: Founder[] = [
  {
    id: "f1",
    name: "Priya Shah",
    email: "priya@novagrid.io",
    role: "CTO & Co-founder",
    company: "NovaGrid",
    bio: "Former Tesla energy systems lead. Built grid optimization platforms at scale.",
    previousExits: 1,
    yearsExperience: 14,
    education: ["Stanford MS EE", "IIT Bombay BTech"],
    skills: ["Energy systems", "ML ops", "Hardware"],
    createdAt: "2026-01-12T00:00:00Z",
  },
  {
    id: "f2",
    name: "Marcus Chen",
    email: "marcus@lattice.ai",
    role: "CEO & Founder",
    company: "Lattice AI",
    bio: "Ex-Google Brain. Two-time founder with a prior $180M acquisition.",
    previousExits: 1,
    yearsExperience: 12,
    education: ["MIT PhD CS", "Berkeley BS"],
    skills: ["LLMs", "Enterprise sales", "Product"],
    createdAt: "2026-02-03T00:00:00Z",
  },
  {
    id: "f3",
    name: "Elena Vargas",
    email: "elena@harbor.health",
    role: "CEO",
    company: "Harbor Health",
    bio: "Physician-founder. Built clinical workflows used by 40+ health systems.",
    previousExits: 0,
    yearsExperience: 16,
    education: ["Harvard MD", "Yale BA"],
    skills: ["Clinical ops", "FHIR", "Go-to-market"],
    createdAt: "2026-03-21T00:00:00Z",
  },
  {
    id: "f4",
    name: "Jordan Blake",
    email: "jordan@pulsepay.io",
    role: "CEO",
    company: "PulsePay",
    bio: "Ex-Stripe product lead. Specializes in cross-border payments infrastructure.",
    previousExits: 0,
    yearsExperience: 10,
    education: ["Wharton MBA", "UCLA BS"],
    skills: ["Payments", "Compliance", "Growth"],
    createdAt: "2026-04-08T00:00:00Z",
  },
  {
    id: "f5",
    name: "Amira Okonkwo",
    email: "amira@orbitalops.space",
    role: "CEO & Co-founder",
    company: "Orbital Ops",
    bio: "Former SpaceX mission ops. Building autonomous satellite fleet software.",
    previousExits: 0,
    yearsExperience: 11,
    education: ["Caltech MS", "Georgia Tech BS"],
    skills: ["Aerospace", "Autonomy", "Systems"],
    createdAt: "2026-05-01T00:00:00Z",
  },
];

export const startups: Startup[] = [
  {
    id: "s1",
    name: "NovaGrid",
    tagline: "AI-native grid optimization for utilities",
    sector: "Climate Tech",
    stage: "due_diligence",
    location: "San Francisco, CA",
    foundedYear: 2023,
    website: "https://novagrid.io",
    fundingRaised: 4_200_000,
    valuation: 42_000_000,
    employeeCount: 28,
    founderIds: ["f1"],
    description:
      "NovaGrid helps utilities reduce curtailment and peak load costs with real-time ML forecasting.",
    traction: "$2.1M ARR · 6 utility LOIs · 94% retention",
    createdAt: "2026-01-12T00:00:00Z",
  },
  {
    id: "s2",
    name: "Lattice AI",
    tagline: "Enterprise agents that ship production workflows",
    sector: "Enterprise AI",
    stage: "term_sheet",
    location: "New York, NY",
    foundedYear: 2022,
    fundingRaised: 18_000_000,
    valuation: 120_000_000,
    employeeCount: 64,
    founderIds: ["f2"],
    description:
      "Lattice builds secure agent infrastructure for Fortune 500 knowledge work automation.",
    traction: "$9.4M ARR · 22 enterprise logos · NDR 142%",
    createdAt: "2026-02-03T00:00:00Z",
  },
  {
    id: "s3",
    name: "Harbor Health",
    tagline: "Ambient clinical documentation for hospitals",
    sector: "HealthTech",
    stage: "screening",
    location: "Boston, MA",
    foundedYear: 2024,
    fundingRaised: 1_800_000,
    valuation: 18_000_000,
    employeeCount: 19,
    founderIds: ["f3"],
    description:
      "Harbor reduces physician documentation burden with specialty-tuned ambient AI.",
    traction: "3 health systems live · 40% time saved · SOC2 in progress",
    createdAt: "2026-03-21T00:00:00Z",
  },
];

export const memos: InvestmentMemo[] = [
  {
    id: "m1",
    startupId: "s2",
    startupName: "Lattice AI",
    title: "Series A Investment Memo — Lattice AI",
    author: "Alex Rivera",
    status: "approved",
    recommendation: "invest",
    conviction: 86,
    riskLevel: "medium",
    summary:
      "Lattice is emerging as a category leader in enterprise agent infrastructure with strong retention and expanding ACV.",
    thesis:
      "Enterprises will consolidate on a secure agent runtime layer. Lattice owns workflow reliability, policy controls, and evaluation — the hard parts competitors underinvest in.",
    market:
      "TAM ~$48B by 2030 across enterprise automation and AI ops tooling. SAM focused on Fortune 2000 knowledge work is ~$9B.",
    team: "Repeat founder with prior exit. Deep technical bench from Google Brain and OpenAI alumni.",
    product:
      "Differentiated eval harness, SOC2 + VPC deployment, and proprietary memory graph for long-running agents.",
    risks: [
      "Hyperscaler platform risk",
      "Sales cycle length for regulated buyers",
      "Talent competition in applied research",
    ],
    askAmount: 12_000_000,
    proposedOwnership: 12.5,
    createdAt: "2026-06-01T00:00:00Z",
    updatedAt: "2026-07-10T00:00:00Z",
  },
  {
    id: "m2",
    startupId: "s1",
    startupName: "NovaGrid",
    title: "Seed Extension Memo — NovaGrid",
    author: "Sam Okada",
    status: "review",
    recommendation: "invest",
    conviction: 74,
    riskLevel: "medium",
    summary:
      "NovaGrid shows clear product-market fit with utilities and a path to multi-year SaaS contracts.",
    thesis:
      "Grid volatility and renewables penetration create urgent demand for forecasting + dispatch optimization software.",
    market:
      "US utility software spend is growing mid-teens. Addressable spend for grid AI ops ~$6B.",
    team: "Strong domain expertise from Tesla Energy. Need to deepen commercial leadership.",
    product:
      "Real-time forecasting with measurable curtailment reduction. Hardware integrations are a moat and a delivery risk.",
    risks: [
      "Long utility procurement cycles",
      "Integration complexity",
      "Capital intensity of pilots",
    ],
    askAmount: 8_000_000,
    proposedOwnership: 15,
    createdAt: "2026-06-20T00:00:00Z",
    updatedAt: "2026-07-16T00:00:00Z",
  },
  {
    id: "m3",
    startupId: "s3",
    startupName: "Harbor Health",
    title: "Screening Memo — Harbor Health",
    author: "Jordan Lee",
    status: "draft",
    recommendation: "watch",
    conviction: 61,
    riskLevel: "high",
    summary:
      "Compelling clinical founder story; needs clearer differentiation vs. ambient documentation incumbents.",
    thesis:
      "Specialty-tuned ambient documentation can win in complex specialties if accuracy and EHR write-back are superior.",
    market: "Clinical documentation AI is crowded; winners will be defined by specialty depth and workflow embed.",
    team: "Physician-CEO is a strength for trust and product sense.",
    product: "Early specialty accuracy gains are promising but sample sizes are small.",
    risks: [
      "Incumbent competition",
      "HIPAA / liability exposure",
      "EHR partnership dependency",
    ],
    askAmount: 5_500_000,
    proposedOwnership: 18,
    createdAt: "2026-07-01T00:00:00Z",
    updatedAt: "2026-07-15T00:00:00Z",
  },
];

export const searchResults: SearchResult[] = [
  {
    id: "sr1",
    type: "startup",
    title: "Lattice AI",
    subtitle: "Enterprise AI · Term sheet",
    snippet:
      "Enterprise agents that ship production workflows. $9.4M ARR, 22 logos.",
    score: 0.94,
    href: "/founders",
  },
  {
    id: "sr2",
    type: "memo",
    title: "Series A Investment Memo — Lattice AI",
    subtitle: "Approved · Conviction 86",
    snippet:
      "Category leader in enterprise agent infrastructure with strong retention...",
    score: 0.91,
    href: "/memos/m1",
  },
  {
    id: "sr3",
    type: "founder",
    title: "Marcus Chen",
    subtitle: "CEO · Lattice AI",
    snippet: "Ex-Google Brain. Two-time founder with a prior $180M acquisition.",
    score: 0.88,
    href: "/founders",
  },
  {
    id: "sr4",
    type: "startup",
    title: "NovaGrid",
    subtitle: "Climate Tech · Due diligence",
    snippet: "AI-native grid optimization. $2.1M ARR, 6 utility LOIs.",
    score: 0.82,
    href: "/founders",
  },
];

export const dealFlowByMonth = [
  { month: "Jan", deals: 8, invested: 2 },
  { month: "Feb", deals: 11, invested: 1 },
  { month: "Mar", deals: 9, invested: 0 },
  { month: "Apr", deals: 14, invested: 2 },
  { month: "May", deals: 12, invested: 1 },
  { month: "Jun", deals: 16, invested: 2 },
  { month: "Jul", deals: 13, invested: 1 },
];
